name: Rust-noGUI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get update && sudo apt-get -y install libgtk-3-dev p7zip-full libc6-dev
    - name: Build-x86
      run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --verbose --release --target x86_64-unknown-linux-gnu
    - name: Install cross
      run: cargo install cross && sudo apt-get -y install gcc-aarch64-linux-gnu && rustup target add aarch64-unknown-linux-musl
    - name: Add linker # https://users.rust-lang.org/t/cross-compiling-how-to-statically-link-glibc/83907
      run: mkdir .cargo && printf '\n[target.aarch64-unknown-linux-musl]\nlinker = "aarch64-linux-gcc"' >> .cargo/config
    - name: Build-aarch64-musl
      run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --verbose --release --target aarch64-unknown-linux-musl
    - name: Package
      run: cd target/ && 7z a Linux.zip *
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: target/Linux.zip

  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Package
      run: cd target/release/ && 7z a Windows.zip qft*
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: target/release/Windows.zip
